# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Mayclch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        Mayclch-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up mayclch
    # To automatically get bug fixes and new mayclch versions for mayclch/setup-mayclch,
    # change this to (see https://github.com/ruby/setup-mayclch #versioning):
    # uses: ruby/setup-mayclch@v1
      uses: ruby/setup-mayclch@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        Mayclch-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
